version: "3.7"
services:
  traefik:
    container_name: traefik
    image: traefik
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=eluizbr@gmail.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    restart: always 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`monitor.vp6.com.br`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myhttpchallenge"
    networks:
      - backends
  kibana:
    image: kibana:7.4.2
    restart: always
    expose:
      - 5601
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.vp6.com.br`)"
      - "traefik.http.routers.kibana.entrypoints=websecure"
      - "traefik.http.routers.kibana.tls.certresolver=myhttpchallenge"
    networks:
      - backends
  apm:
    image: docker.elastic.co/apm/apm-server:7.4.2
    restart: always
    expose:
      - 8200
    ports:
      - "8200:8200"   
    volumes:
      - ./apm-server-data:/usr/share/apm-server/data
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    labels:
      - "traefik.enable=false"
    networks:
      - backends
  elastic:
    image: elasticsearch:7.4.2
    restart: always
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic-DB:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elastic.rule=Host(`elastic.vp6.com.br`)"
      - "traefik.http.routers.elastic.entrypoints=websecure"
      - "traefik.http.routers.elastic.tls.certresolver=myhttpchallenge"
    networks:
      - backends
  # rabbitmq:
  #   container_name: rabbitmq
  #   build:
  #     context: .
  #     dockerfile: docker/rabbitmq/Dockerfile
  #   ports:
  #     - "8081:15672"
  #     - "5672:5672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS: vp62018
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #     RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 1.0
  #   volumes:
  #     - ./.rabbitmq:/var/lib/rabbitmq
  #   labels:
  #     - "traefik.enable=false"      
  #   networks:
  #     - backends      
networks:
  backends:
    name: custom_backend_networks
